services:
  eureka-server:
    image: "seu_usuario/sua_imagem_docker"
    container_name: "eureka-server"
    ports:
      - 8761:8761

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: suasenha
      POSTGRES_DB: ms-product
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  product:
    image: "seu_usuario/sua_imagem_docker"
    container_name: "ms-product"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ms-product
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=suasenha
    ports:
      - "8082:8082"
    depends_on:
      - postgres
volumes:
  postgres_data: